# Configuration SonarQube pour projet Python
sonar.projectKey=Projet-python
sonar.organization=khalidouatik
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=coverage.xml
sonar.login=${{ secrets.SONAR_TOKEN }}
