- name: Copier le docker-compose.yml dans /opt/monitoring
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/docker/docker-compose.yml"
    dest: /opt/monitoring/docker-compose.yml
    mode: '0644'

- name: Copier le prometheus.yml dans /opt/monitoring
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/docker/prometheus.yml"
    dest: /opt/monitoring/prometheus.yml
    mode: '0644'
